# Generated by Django 4.1.2 on 2023-02-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('body', models.TextField()),
                ('size', models.CharField(choices=[('1x1', '1x1'), ('3x2', '3x2'), ('1x2', '1x2')], default='1x1', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('scheduledFrom', models.DateTimeField()),
                ('scheduledTo', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Banner Ads',
            },
        ),
    ]
