# Generated by Django 4.1.2 on 2023-02-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerad',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bannerad',
            name='image',
            field=models.ImageField(upload_to='bannerads/'),
        ),
        migrations.AlterField(
            model_name='bannerad',
            name='scheduledFrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bannerad',
            name='scheduledTo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
