# Generated by Django 4.1.2 on 2023-03-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_bannerad_body_alter_bannerad_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerad',
            name='size',
            field=models.CharField(choices=[('1x1', '1x1'), ('3x1', '3x1')], default='1x1', max_length=3),
        ),
        migrations.AlterField(
            model_name='bannerad',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
