# Generated by Django 4.1.2 on 2023-03-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
    ]
