# Generated by Django 4.1.2 on 2023-05-10 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v2', '0002_alter_shop_logo'),
        ('analytics', '0002_alter_categoryview_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('Link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkclickcount', to='v2.link')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Link Click',
                'verbose_name_plural': 'Link Clicks',
                'ordering': ['-date'],
            },
        ),
    ]
