# Generated by Django 4.1.2 on 2023-02-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_name_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('user', 'User')], max_length=30, verbose_name='account type'),
        ),
    ]
