# Generated by Django 4.1.2 on 2022-10-25 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ryans',
        ),
        migrations.RemoveField(
            model_name='product',
            name='startech',
        ),
        migrations.RemoveField(
            model_name='product',
            name='techland',
        ),
        migrations.AddField(
            model_name='ryans',
            name='product',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ryans', to='v1.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startech',
            name='product',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='startech', to='v1.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techland',
            name='product',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='techland', to='v1.product'),
            preserve_default=False,
        ),
    ]
