# Generated by Django 4.1.2 on 2023-02-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
