# Generated by Django 4.1.2 on 2023-02-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0011_category_slug_product_slug_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
