# Generated by Django 4.1.2 on 2023-02-09 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0013_product_color_alter_product_best_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
